-- Optional cloud schema for Supabase mode.
-- The Flask backend uses the server-side service key and scopes every
-- application query by user_id. For a browser-direct Supabase Auth version,
-- replace this with auth.uid()-based UUID keys and RLS policies.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz default now()
);

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  age integer,
  height_cm numeric,
  weight_kg numeric,
  activity_level text,
  dietary_preference text,
  goal text,
  allergies text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.diet_plans (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  breakfast text not null,
  lunch text not null,
  snack text not null,
  dinner text not null,
  nutrition_summary text not null,
  created_at timestamptz default now()
);

create table if not exists public.user_files (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  filename text not null,
  storage_path text not null,
  uploaded_at timestamptz default now()
);

-- Recommended production hardening if you move user authentication directly
-- into Supabase Auth: enable RLS and use auth.uid() policies.
-- Do not expose SUPABASE_SERVICE_KEY to the browser.
